#!/bin/sh

################################################################################
# A script to report new available packages on HomeServer and push notification 
# to `ntfy.sh` server.
################################################################################

set -e

if apt update 2> /dev/null | grep "apt list --upgradable"
then
	curl \
		-d " $(apt list --upgradable 2> /dev/null | sed -e "s|Listing...||g" -e "s|/.*$||g") " \
		-H "Title: NEW PACKAGES on $(hostname)" \
		-H "Priority: High" \
		http://192.168.1.32:9085/General
		#URL_of_ntfy.sh_server/topic
fi
